services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
    environment:
      - MELI_SERVICE=${MELI_SERVICE}
    ports:
      - "8080:8080"
  redis:
    hostname: redis
    image: redis:latest

